# Generated by Django 2.2.8 on 2021-10-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('zona', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('precio', models.IntegerField()),
                ('arrendado', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('cable', models.BooleanField()),
                ('servicioHabitacion', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='')),
                ('parking', models.BooleanField()),
                ('piscina', models.BooleanField()),
                ('restaurante', models.BooleanField()),
            ],
        ),
    ]
