# Generated by Django 2.2.8 on 2021-12-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('usuario_cliente', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=20)),
                ('cantidad_personas', models.IntegerField()),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('arrendado', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('cable', models.BooleanField()),
                ('servicioHabitacion', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('piscina', models.BooleanField()),
                ('restaurante', models.BooleanField()),
                ('amueblado', models.BooleanField()),
                ('calefaccion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiposervicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('rutConductor', models.CharField(max_length=50)),
                ('nombreConductor', models.CharField(max_length=50)),
                ('tipoVehiculo', models.CharField(max_length=50)),
                ('contacto', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('horaInicio', models.CharField(max_length=50)),
                ('horaCierre', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('precio', models.IntegerField()),
                ('horaInicio', models.CharField(max_length=50)),
                ('horaCierre', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Tiposervicio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_pasajero', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Arriendo')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='ActaOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conforme', models.BooleanField()),
                ('multa', models.BooleanField()),
                ('transporte', models.BooleanField()),
                ('condiciones', models.CharField(max_length=50)),
                ('problemas', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='ActaIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField()),
                ('entrega', models.BooleanField()),
                ('transporte', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Tiposervicio')),
            ],
        ),
    ]
