# Generated by Django 2.2.8 on 2021-10-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Departament',
        ),
    ]
