# Generated by Django 2.2.8 on 2021-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='nombre_cliente',
            field=models.CharField(max_length=20),
        ),
    ]
