# Generated by Django 2.2.8 on 2021-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20211203_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='precio_final',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
