# Generated by Django 2.2.8 on 2021-10-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20211012_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Departamento',
        ),
    ]
