# Generated by Django 2.2.8 on 2021-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20211012_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='amueblado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='calefaccion',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
