# Generated by Django 2.2.8 on 2021-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_tarjeta',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
