# Generated by Django 2.2.8 on 2021-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_pago_tipo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
