# Generated by Django 2.2.8 on 2021-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='horario',
            new_name='horaCierre',
        ),
        migrations.AddField(
            model_name='servicio',
            name='horaInicio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
