# Generated by Django 2.2.8 on 2021-12-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0006_pago_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportes_contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(max_length=20)),
            ],
        ),
    ]
