# Generated by Django 2.2.8 on 2021-10-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0006_auto_20211017_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='servicio',
            new_name='tipoServicio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.TipoServicio'),
        ),
    ]
