# Generated by Django 2.2.8 on 2021-10-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0008_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona'),
        ),
    ]
