# Generated by Django 2.2.8 on 2021-10-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0010_remove_departamento_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
