# Generated by Django 2.2.8 on 2021-10-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0011_auto_20211017_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('precio', models.IntegerField()),
                ('arrendado', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('cable', models.BooleanField()),
                ('servicioHabitacion', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='')),
                ('parking', models.BooleanField()),
                ('piscina', models.BooleanField()),
                ('restaurante', models.BooleanField()),
                ('amueblado', models.BooleanField()),
                ('calefaccion', models.BooleanField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona')),
            ],
        ),
    ]
