# Generated by Django 2.2.8 on 2021-10-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0013_tiposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('precio', models.IntegerField()),
                ('horaInicio', models.CharField(max_length=50)),
                ('horaCierre', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.TipoServicio')),
            ],
        ),
    ]
