# Generated by Django 2.2.8 on 2021-10-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0015_servicio_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='tipoServicio',
            new_name='Servicio',
        ),
    ]
