# Generated by Django 2.2.8 on 2021-10-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0018_auto_20211019_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Tiposervicio'),
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('rutConductor', models.CharField(max_length=50)),
                ('nombreConductor', models.CharField(max_length=50)),
                ('tipoVehiculo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('horaInicio', models.CharField(max_length=50)),
                ('horaCierre', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Departamento')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamento.Zona')),
            ],
        ),
    ]
